### ISSUE TITLE
How can I display authenticated user name in home page

### ISSUE THREAD

**Issue by swalihvmbazar** [alper-efe-sahin/flutter_firebase_ddd_bloc_2022#62]

**Comment by FlutterWiz** [comment]
We have such getter:

```dart
  @override
  Future<Option<User>> getSignedInUser() async =>
      optionOf(_firebaseAuth.currentUser?.toDomain());

```

Using this information, you can get the user's name. In this repository, we have just an **id**, so you need to create a **name** inside the user model also. After that, carry it to the state.

Finally, using **blocbuilder**, you can show the user's name from the state.

**Comment by swalihvmbazar** [comment]
I defined a state in auth state User user
`part of 'auth_bloc.dart';

@freezed
class AuthState with _$AuthState {
  const factory AuthState({User? user}) = _AuthState;
  const factory AuthState.initial() = _Initial;
  const factory AuthState.authenticated() = Authenticated;
  const factory AuthState.unauthenticated() = Unauthenticated;
}`

`return BlocListener<AuthBloc, AuthState>(
      listener: (context, state) {
        state.maybeMap(
          unauthenticated: (_) {
            context.router.replace(const SignInRoute());
          },
          orElse: () {},
        );
      },
      child:Text('Halo'))`

I got an error in vscode that is 1 positional argument(s) expected, but 0 found.
Try adding the missing arguments. in unauthenticated method in maybeMap

**Comment by FlutterWiz** [comment]
I did not understand the exact problem actually. So, It says missing arguments exception. So put the argument to there. 

From here, I see you created new state objects. You can put them into the AuthState (I mean combine them). Generally I do such things like this. 

```dart
AuthState({required bool isUserLoggedIn, required User user})
```
